import random

fr1 = str('A vida trará coisas boas se tiver paciência.')
fr2 = str('Demonstre amor e alegria em todas as oportunidades e verá que a paz nasce dentro de si.')
fr3 = str('Não compense na ira o que lhe falta na razão.')
fr4 = str('Defeitos e virtudes são apenas dois lados da mesma moeda.')
fr5 = str('A maior de todas as torres começa no solo.')
fr6 = str('Não há que ser forte. Há que ser flexível.')
fr7 = str('Todos os dias organiza os seus cabelos, por que não faz o mesmo com o coração?')
fr8 = str('Há três coisas que jamais voltam; a flecha lançada, a palavra dita e a oportunidade perdida.')
fr9 = str('A juventude não é uma época da vida, é um estado de espírito.')
fr10 = str('Podemos escolher o que semear, mas somos obrigados a colher o que plantamos.')
fr11 = str('Dê toda a atenção á formação dos seus filhos, sobretudo com bons exemplos da sua própria vida.')
fr12 = str('Siga os bons e aprenda com eles.')
fr13 = str('Não importa o tamanho da montanha, ela não pode tapar o sol.')
fr14 = str('O bom-senso vale mais do que muito conhecimento.')
fr15 = str('Quem quer colher rosas tem de estar preparado para suportar os espinhos.')
fr16 = str('São os nossos amigos que nos ensinam as mais valiosas lições.')
fr17 = str('Aquele que se importa com o sentimento dos outros, não é um tolo.')
fr18 = str('A adversidade é um espelho que reflete o verdadeiro eu.')
fr19 = str('Lamentar aquilo que não temos é desperdiçar aquilo que já possuímos.')
fr20 = str('Uma bela flor é incompleta sem as suas folhas.')
fr21 = str('Sem o fogo do entusiasmo, não há o calor da vitória.')
fr22 = str('Os defeitos são mais fortes quando o amor é fraco.')
fr23 = str('Amizade e Amor são coisas que se unem num piscar de olhos.')
fr24 = str('Surpreender e ser surpreendido é o segredo do amor.')
fr25 = str('Faça pequenas coisas hoje e coisas maiores lhe serão confiadas amanhã.')
fr26 = str('A paciência na adversidade é sinal de um coração sensível.')
fr27 = str('A sorte favorece a mente bem preparada.')
fr28 = str('A sua visão se tornará mais clara apenas quando conseguir olhar para dentro do seu coração.')
fr29 = str('Quem olha para fora sonha; quem olha para dentro acorda.')
fr30 = str('As pessoas esquecerão o que você disse e o que você fez… mas nunca esquecerão como se sentiram.')
fr31 = str('Espere pelo mais sábio dos conselhos: o tempo.')
fr32 = str('Todas as coisas são difíceis antes de se tornarem fáceis.')
fr33 = str('Se você se sente só é porque construiu muros ao invés de pontes.')
fr34 = str('Vencer é 90 por cento suor e 10 por cento de engenho.')
fr35 = str('O amor está sempre mais próximo do que você imagina.')
fr36 = str('Você é do tamanho do seu sonho.')
fr37 = str('Pare de procurar eternamente; a felicidade está mesmo aqui ao seu lado.')
fr38 = str('O conhecimento é a única virtude e a ignorância é o único vício.')
fr39 = str('O nosso primeiro e último amor é… o amor-próprio.')
fr40 = str('Deixe de lado as preocupações e seja feliz.')
fr41 = str('A vontade das pessoas é a melhor das leis.')
fr42 = str('Nós somos o que pensamos.')
fr43 = str('A maior barreira para o sucesso é o medo do fracasso.')
fr44 = str('O pessimista vê a dificuldade em cada oportunidade; O otimista vê a oportunidade em cada dificuldade.')
fr45 = str('Muitas das grandes realizações do mundo foram feitas por homens cansados e desanimados que continuaram o seu trabalho.')
fr46 = str('O insucesso é apenas uma oportunidade para recomeçar de novo com mais experiência.')
fr47 = str('Coragem é a resistência ao medo, domínio do medo, e não a ausência do medo.')
fr48 = str('O verdadeiro homem mede a sua força, quando se defronta com o obstáculo.')
fr49 = str('Quem quer vencer um obstáculo deve armar-se da força do leão e da prudência da serpente.')
fr50 = str('A adversidade desperta em nós capacidades que, em circunstâncias favoráveis, teriam ficado adormecidas.')
fr51 = str('Motivação não é sinónimo de transformação, mas um passo em sua direção.')
fr52 = str('O que empobrece o ser humano, não é a falta de dinheiro, mais sim, a falta de fé,motivação e criatividade.')
fr53 = str('A inspiração vem dos outros. A motivação vem de dentro de nós.')
fr54 = str('Não acredite mais em pessoas especiais, mas em momentos especiais com pessoas normais.')
fr55 = str('A nossa vida tem 4 sentidos… Amar, Sofrer, Lutar e Vencer. Ame muito, sofra pouco, lute bastante e vença sempre!')
fr56 = str('Nada é por acaso… Acredite em seus sonhos e nos seus potenciais….Na vida tudo se supera..')
fr57 = str('Acredite em milagres, mas não dependa deles.')
fr58 = str('Você sempre será a sua melhor companhia!')
fr59 = str('Realize o óbvio, pense no improvável e conquiste o impossível.')
fr60 = str('O riso é a menor distância entre duas pessoas.')

print(random.choice([fr1, fr2, fr3, fr4, fr5, fr6, fr7, fr8, fr9, fr10, fr11, fr12, fr13, fr14, fr15, fr16, fr17, fr18, fr19,
                     fr20, fr21, fr22, fr23, fr24, fr25, fr26, fr27, fr28, fr29, fr30, fr31, fr32, fr33, fr34, fr35, fr36, fr37, fr38, fr39, fr40,
                     fr41, fr42, fr43, fr44, fr45, fr46, fr47, fr48, fr49, fr50, fr51, fr52, fr53, fr54, fr55, fr56, fr57, fr58, fr59, fr60]))
print(';)')

